// <auto-generated>
//  Generated by Sailwind.ApiGen 0.1.0 — do not edit by hand.
//  Regenerate with `make codegen` (requires lib/Assembly-CSharp.dll).
// </auto-generated>

using Xunit;

namespace Sailwind.Api.SurfaceTests
{
    /// <summary>One fact per manifest entry, re-verified against lib/ via Cecil.
    /// Each fact no-ops when the game assembly is absent (see SurfaceProbe).</summary>
    public sealed class SurfaceContractTests
    {
        [Fact]
        public void BoatMooringManager_type() => SurfaceProbe.RequireType("BoatMooringManager");

        [Fact]
        public void BoatRefs_type() => SurfaceProbe.RequireType("BoatRefs");

        [Fact]
        public void Currency_type() => SurfaceProbe.RequireType("Currency");

        [Fact]
        public void GameState_type() => SurfaceProbe.RequireType("GameState");

        [Fact]
        public void IslandMarket_type() => SurfaceProbe.RequireType("IslandMarket");

        [Fact]
        public void NPCBoatController_type() => SurfaceProbe.RequireType("NPCBoatController");

        [Fact]
        public void PlayerGold_type() => SurfaceProbe.RequireType("PlayerGold");

        [Fact]
        public void SaveLoadManager_type() => SurfaceProbe.RequireType("SaveLoadManager");

        [Fact]
        public void SaveSlots_type() => SurfaceProbe.RequireType("SaveSlots");

        [Fact]
        public void Sun_type() => SurfaceProbe.RequireType("Sun");

        [Fact]
        public void Wind_type() => SurfaceProbe.RequireType("Wind");

    }
}
