using System;
using System.Collections.Generic;
using System.IO;
using System.Text;

namespace Sailwind.ApiGen
{
    /// <summary>
    /// Projects the verified surface into the committed generated artifacts:
    /// <c>GameRef.g.cs</c>, <c>manifest/api-surface.json</c> (+ <c>.sha256</c>),
    /// <c>SurfaceManifest.g.cs</c>, and <c>SurfaceContract.g.cs</c>.
    /// </summary>
    public static class CodeEmitter
    {
        private const string GeneratedHeader =
            "// <auto-generated>\n" +
            "//  Generated by " + ToolInfo.Name + " " + ToolInfo.Version + " — do not edit by hand.\n" +
            "//  Regenerate with `make codegen` (requires lib/Assembly-CSharp.dll).\n" +
            "// </auto-generated>\n";

        public static SurfaceDoc BuildDoc(
            string gameBuildId,
            Guid mvid,
            IReadOnlyList<ResolvedEntry> resolved)
        {
            var doc = new SurfaceDoc
            {
                Header = new SurfaceHeader
                {
                    AssemblyMvid = mvid.ToString("D"),
                    GameBuildId = string.IsNullOrEmpty(gameBuildId) ? "unprovisioned" : gameBuildId,
                },
            };
            foreach (var r in resolved)
            {
                doc.Members.Add(new SurfaceEntry
                {
                    Type = r.Source.Type,
                    Member = r.Source.Member,
                    Kind = r.Source.Kind,
                    Static = r.Source.Static,
                    Signature = r.Signature,
                });
            }
            return doc;
        }

        public static void WriteManifest(RepoPaths paths, SurfaceDoc doc)
        {
            var json = CanonicalJson.Serialize(doc);
            var hash = CanonicalJson.Sha256Hex(json);
            WriteAllTextLf(paths.ManifestJson, json);
            WriteAllTextLf(paths.ManifestSha256, hash + "\n");
        }

        public static void WriteGameRef(RepoPaths paths, IReadOnlyList<ResolvedEntry> resolved)
        {
            var sb = new StringBuilder();
            sb.Append(GeneratedHeader);
            sb.Append("\nnamespace Sailwind.Api.Generated\n{\n");
            sb.Append("    /// <summary>Verified game-member names — the single source of magic strings\n");
            sb.Append("    /// for Harmony patches and reflection binders. Empty until seeded members are\n");
            sb.Append("    /// resolved against the real assembly.</summary>\n");
            sb.Append("    internal static class GameRef\n    {\n");

            var used = new HashSet<string>(StringComparer.Ordinal);
            foreach (var r in resolved)
            {
                string name, value;
                if (r.Source.Kind == Kinds.Type)
                {
                    name = Ident(r.Source.Type);
                    value = r.Source.Type;
                }
                else
                {
                    name = Ident(r.Source.Type) + "_" + Ident(r.Source.Member);
                    value = r.Source.Member;
                }
                if (!used.Add(name)) continue;
                sb.Append($"        public const string {name} = {CString(value)};\n");
            }

            sb.Append("    }\n}\n");
            WriteAllTextLf(paths.GameRefFile, sb.ToString());
        }

        public static void WriteSurfaceManifest(
            RepoPaths paths, SurfaceDoc doc, string canonicalJson, string hash)
        {
            var sb = new StringBuilder();
            sb.Append(GeneratedHeader);
            sb.Append("\nusing Sailwind.Api;\n\nnamespace Sailwind.Api.Generated\n{\n");
            sb.Append("    /// <summary>Surface manifest embedded as consts so the plugin needs no file I/O\n");
            sb.Append("    /// at runtime. The runtime surface check reflects over the loaded game assembly\n");
            sb.Append("    /// using <see cref=\"Members\"/> and compares against <see cref=\"Hash\"/>.</summary>\n");
            sb.Append("    internal static class SurfaceManifest\n    {\n");
            sb.Append($"        public const string GameBuildId = {CString(doc.Header.GameBuildId)};\n");
            sb.Append($"        public const string Hash = {CString(hash)};\n");
            sb.Append($"        public const string Json = {CString(canonicalJson)};\n\n");
            sb.Append("        public static readonly SurfaceMember[] Members = new SurfaceMember[]\n        {\n");
            foreach (var m in SortedForEmit(doc.Members))
            {
                sb.Append($"            new SurfaceMember({CString(m.Type)}, {CString(m.Member)}, " +
                          $"{CString(m.Kind)}, {(m.Static ? "true" : "false")}),\n");
            }
            sb.Append("        };\n    }\n}\n");
            WriteAllTextLf(paths.SurfaceManifestFile, sb.ToString());
        }

        public static void WriteSurfaceContract(RepoPaths paths, SurfaceDoc doc)
        {
            var sb = new StringBuilder();
            sb.Append(GeneratedHeader);
            sb.Append("\nusing Xunit;\n\nnamespace Sailwind.Api.SurfaceTests\n{\n");
            sb.Append("    /// <summary>One fact per manifest entry, re-verified against lib/ via Cecil.\n");
            sb.Append("    /// Each fact no-ops when the game assembly is absent (see SurfaceProbe).</summary>\n");
            sb.Append("    public sealed class SurfaceContractTests\n    {\n");

            var used = new HashSet<string>(StringComparer.Ordinal);
            foreach (var m in SortedForEmit(doc.Members))
            {
                string method = Ident(m.Type) + (m.Kind == Kinds.Type ? "" : "_" + Ident(m.Member)) + "_" + m.Kind;
                var baseName = method;
                int n = 1;
                while (!used.Add(method)) method = baseName + "_" + (++n);

                sb.Append("        [Fact]\n");
                if (m.Kind == Kinds.Type)
                    sb.Append($"        public void {method}() => SurfaceProbe.RequireType({CString(m.Type)});\n\n");
                else
                    sb.Append($"        public void {method}() => SurfaceProbe.RequireMember({CString(m.Type)}, " +
                              $"{CString(m.Member)}, {CString(m.Kind)}, {(m.Static ? "true" : "false")});\n\n");
            }

            sb.Append("    }\n}\n");
            WriteAllTextLf(paths.SurfaceContractFile, sb.ToString());
        }

        private static IEnumerable<SurfaceEntry> SortedForEmit(List<SurfaceEntry> members)
        {
            var copy = new List<SurfaceEntry>(members);
            copy.Sort((a, b) =>
            {
                int c = string.CompareOrdinal(a.Type, b.Type);
                if (c != 0) return c;
                c = string.CompareOrdinal(a.Member, b.Member);
                if (c != 0) return c;
                return string.CompareOrdinal(a.Kind, b.Kind);
            });
            return copy;
        }

        private static string Ident(string raw)
        {
            if (string.IsNullOrEmpty(raw)) return "_";
            var sb = new StringBuilder(raw.Length);
            foreach (var ch in raw)
                sb.Append(char.IsLetterOrDigit(ch) || ch == '_' ? ch : '_');
            if (char.IsDigit(sb[0])) sb.Insert(0, '_');
            return sb.ToString();
        }

        private static string CString(string s)
        {
            if (s == null) return "null";
            var sb = new StringBuilder(s.Length + 2);
            sb.Append('"');
            foreach (var ch in s)
            {
                switch (ch)
                {
                    case '"': sb.Append("\\\""); break;
                    case '\\': sb.Append("\\\\"); break;
                    case '\n': sb.Append("\\n"); break;
                    case '\r': sb.Append("\\r"); break;
                    case '\t': sb.Append("\\t"); break;
                    default:
                        if (ch < 0x20) sb.Append("\\u").Append(((int)ch).ToString("x4"));
                        else sb.Append(ch);
                        break;
                }
            }
            sb.Append('"');
            return sb.ToString();
        }

        private static void WriteAllTextLf(string path, string content)
        {
            Directory.CreateDirectory(Path.GetDirectoryName(path));
            File.WriteAllText(path, content, new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
        }
    }
}
