// protocol-smoke: the init-0 conformance harness and PoC test client.
//
// Usage:
//   dotnet run --project tools/protocol-smoke -- --server <path-to-sw-server>
//   SW_SERVER_BIN=<path> dotnet run --project tools/protocol-smoke
//   make smoke   (builds server --release, then runs with the default path)
//
// The harness spawns its own server against a throwaway temp-dir SQLite db,
// waits for the "listening on <addr>" readiness line, and runs the seven
// numbered checks. Exit code 0 only if every check passes.

using System;
using System.Globalization;
using System.IO;
using System.Runtime.InteropServices;

namespace Sailwind.ProtocolSmoke
{
    internal static class Program
    {
        private static int Main(string[] args)
        {
            var serverPath = ResolveServerPath(args);
            if (string.IsNullOrEmpty(serverPath))
            {
                Console.Error.WriteLine(
                    "error: no server binary. Pass --server <path>, set SW_SERVER_BIN, or build it (make server-build).");
                return 2;
            }

            if (!File.Exists(serverPath))
            {
                Console.Error.WriteLine($"error: server binary not found at '{serverPath}'.");
                return 2;
            }

            var port = ParsePort(args, 38455);

            var tempDir = Path.Combine(Path.GetTempPath(), "sw-smoke-" + Guid.NewGuid().ToString("N"));
            Directory.CreateDirectory(tempDir);
            var dbPath = Path.Combine(tempDir, "smoke.sqlite");
            var configPath = WriteConfig(tempDir, dbPath, port);

            Console.WriteLine("Sailwind Online protocol-smoke");
            Console.WriteLine($"info  server binary: {serverPath}");
            Console.WriteLine($"info  temp db:       {dbPath}");

            var checks = new Checks(serverPath, configPath, tempDir);
            bool allPass;
            try
            {
                allPass = checks.Run();
            }
            finally
            {
                TryCleanup(tempDir);
            }

            return allPass ? 0 : 1;
        }

        private static string ResolveServerPath(string[] args)
        {
            var fromArg = GetOption(args, "--server");
            if (!string.IsNullOrEmpty(fromArg))
            {
                return fromArg;
            }

            var fromEnv = Environment.GetEnvironmentVariable("SW_SERVER_BIN");
            if (!string.IsNullOrEmpty(fromEnv))
            {
                return fromEnv;
            }

            var exe = RuntimeInformation.IsOSPlatform(OSPlatform.Windows) ? "sw-server.exe" : "sw-server";
            foreach (var candidate in DefaultServerCandidates(exe))
            {
                if (File.Exists(candidate))
                {
                    return candidate;
                }
            }

            return null;
        }

        // Looks for the release binary relative to the current directory (the
        // repo root under `make smoke`) and walking up from the app base dir.
        private static System.Collections.Generic.IEnumerable<string> DefaultServerCandidates(string exe)
        {
            var rel = Path.Combine("server", "target", "release", exe);
            yield return Path.GetFullPath(rel);

            var dir = AppContext.BaseDirectory;
            for (var i = 0; i < 8 && dir != null; i++)
            {
                yield return Path.Combine(dir, rel);
                dir = Path.GetDirectoryName(dir.TrimEnd(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar));
            }
        }

        private static string WriteConfig(string dir, string dbPath, int port)
        {
            var configPath = Path.Combine(dir, "config.toml");
            // Forward slashes keep the path valid inside a TOML basic string on
            // every platform, including Windows.
            var db = dbPath.Replace('\\', '/');
            var contents =
                "# Generated by protocol-smoke. Ephemeral; safe to delete.\n" +
                $"bind = \"127.0.0.1:{port.ToString(CultureInfo.InvariantCulture)}\"\n" +
                $"db = \"{db}\"\n" +
                "server_name = \"protocol-smoke\"\n" +
                "tick_hz = 30\n" +
                "snapshot_hz = 4\n" +
                // Check 3 bounds B's first hello exchange to half a second after
                // B is already transport-connected. This one-second gate makes
                // the exact transient response an enforced precondition rather
                // than a scheduler-dependent observation.
                "new_session_min_interval_ms = 1000\n";
            File.WriteAllText(configPath, contents);
            return configPath;
        }

        private static int ParsePort(string[] args, int fallback)
        {
            var raw = GetOption(args, "--port");
            if (!string.IsNullOrEmpty(raw) && int.TryParse(raw, NumberStyles.Integer, CultureInfo.InvariantCulture, out var port))
            {
                return port;
            }

            return fallback;
        }

        private static string GetOption(string[] args, string name)
        {
            for (var i = 0; i < args.Length - 1; i++)
            {
                if (string.Equals(args[i], name, StringComparison.Ordinal))
                {
                    return args[i + 1];
                }
            }

            return null;
        }

        private static void TryCleanup(string dir)
        {
            try
            {
                Directory.Delete(dir, recursive: true);
            }
            catch (IOException)
            {
                // The server may still hold the db file briefly; leaving a temp
                // dir behind is harmless.
            }
            catch (UnauthorizedAccessException)
            {
            }
        }
    }
}
