<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <AssemblyName>Sailwind.Contracts</AssemblyName>
    <RootNamespace>Sailwind.Contracts</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Google.FlatBuffers" Version="25.2.10" />
  </ItemGroup>

</Project>
