<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>Sailwind.Online.Sync.Tests</AssemblyName>
    <RootNamespace>Sailwind.Online.Sync.Tests</RootNamespace>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
    <PackageReference Include="xunit" Version="2.9.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\packages\sync\Sailwind.Online.Sync\Sailwind.Online.Sync.csproj" />
    <ProjectReference Include="..\..\packages\api-abstractions\Sailwind.Api.Abstractions\Sailwind.Api.Abstractions.csproj" />
  </ItemGroup>

</Project>
